registry_credentials: &registry_credentials
  username: ((registry.robot))
  password: ((registry.token))

cosign_credentials: &cosign_credentials
  KUBECONFIG_JSON: ((kubeconfig))
  DOCKERCONFIG_JSON: ((registry.config))

git_credentials: &git_credentials
  username: ((github.username))
  password: ((github.password))
  signingkey: ((github.signing_priv_key))

cosign_verify: &cosign_verify
  platform: linux
  image_resource:
    source:
      repository: gcr.io/projectsigstore/cosign
      tag: v2.0.0
    type: registry-image
  inputs:
  - name: image
  run:
    path: /busybox/sh
    args:
      - -c
      - |
        umask 077
        mkdir ${HOME}/.kube
        echo "$KUBECONFIG_JSON" > ${HOME}/.kube/config

        mkdir ${HOME}/.docker
        echo "$DOCKERCONFIG_JSON" > ${HOME}/.docker/config.json

        export REPOSITORY=$(cat image/repository)
        export DIGEST=$(cat image/digest)
        /ko-app/cosign version 
        /ko-app/cosign verify --key k8s://concourse-online-boutique/signing-key $REPOSITORY@$DIGEST 

get_images: &get_images
  steps:
  - get: adservice  
    passed:
    - bump-version
  - get: cartservice  
    passed:
    - bump-version
  - get: checkoutservice  
    passed:
    - bump-version
  - get: currencyservice  
    passed:
    - bump-version
  - get: emailservice  
    passed:
    - bump-version
  - get: frontend  
    passed:
    - bump-version
  - get: paymentservice  
    passed:
    - bump-version
  - get: productcatalogservice  
    passed:
    - bump-version
  - get: recommendationservice  
    passed:
    - bump-version
  - get: shippingservice  
    passed:
    - bump-version

resources:
- name: current-release
  type: git
  icon: github
  source:
    uri: https://github.com/crdant/online-boutique-replicated.git
    branch: main
    paths: 
    - manifests/**
    <<: *git_credentials
- name: next-release
  type: git
  icon: github
  source:
    uri: https://github.com/crdant/online-boutique-replicated.git
    paths: 
    - manifests/**
    <<: *git_credentials
- name: version
  type: semver
  icon: counter
  source:
    driver: git
    uri: https://github.com/crdant/online-boutique-replicated.git
    branch: version
    file: version
    <<: *git_credentials
- name: adservice
  type: registry-image
  icon: oci 
  source:
    repository: registry.shortrib.dev/online-boutique/adservice
    tag: edge
    <<: *registry_credentials
- name: cartservice
  type: registry-image
  icon: oci 
  source:
    repository: registry.shortrib.dev/online-boutique/cartservice
    tag: edge
    <<: *registry_credentials
- name: checkoutservice
  type: registry-image
  icon: oci 
  source:
    repository: registry.shortrib.dev/online-boutique/checkoutservice
    tag: edge
    <<: *registry_credentials
- name: currencyservice
  type: registry-image
  icon: oci 
  source:
    repository: registry.shortrib.dev/online-boutique/currencyservice
    tag: edge
    <<: *registry_credentials
- name: emailservice
  type: registry-image
  icon: oci 
  source:
    repository: registry.shortrib.dev/online-boutique/emailservice
    tag: edge
    <<: *registry_credentials
- name: frontend
  type: registry-image
  icon: oci 
  source:
    repository: registry.shortrib.dev/online-boutique/frontend
    tag: edge
    <<: *registry_credentials
- name: paymentservice
  type: registry-image
  icon: oci 
  source:
    repository: registry.shortrib.dev/online-boutique/paymentservice
    tag: edge
    <<: *registry_credentials
- name: productcatalogservice
  type: registry-image
  icon: oci 
  source:
    repository: registry.shortrib.dev/online-boutique/productcatalogservice
    tag: edge
    <<: *registry_credentials
- name: recommendationservice
  type: registry-image
  icon: oci 
  source:
    repository: registry.shortrib.dev/online-boutique/recommendationservice
    tag: edge
    <<: *registry_credentials
- name: shippingservice
  type: registry-image
  icon: oci 
  source:
    repository: registry.shortrib.dev/online-boutique/shippingservice
    tag: edge
    <<: *registry_credentials

jobs:
- name: verify-adservice
  plan:
  - get: adservice  
    trigger: true
  - task: verify
    input_mapping:
      image: adservice
    params:
      <<: *cosign_credentials
    config:
      <<: *cosign_verify

- name: verify-cartservice
  plan:
  - get: cartservice  
    trigger: true
  - task: verify
    input_mapping:
      image: cartservice
    params:
      <<: *cosign_credentials
    config:
      <<: *cosign_verify

- name: verify-checkoutservice
  plan:
  - get: checkoutservice  
    trigger: true
  - task: verify
    input_mapping:
      image: checkoutservice
    params:
      <<: *cosign_credentials
    config:
      <<: *cosign_verify

- name: verify-currencyservice
  plan:
  - get: currencyservice  
    trigger: true
  - task: verify
    input_mapping:
      image: currencyservice
    params:
      <<: *cosign_credentials
    config:
      <<: *cosign_verify

- name: verify-emailservice
  plan:
  - get: emailservice  
    trigger: true
  - task: verify
    input_mapping:
      image: emailservice
    params:
      <<: *cosign_credentials
    config:
      <<: *cosign_verify

- name: verify-frontend
  plan:
  - get: frontend  
    trigger: true
  - task: verify
    input_mapping:
      image: frontend
    params:
      <<: *cosign_credentials
    config:
      <<: *cosign_verify

- name: verify-paymentservice
  plan:
  - get: paymentservice  
    trigger: true
  - task: verify
    input_mapping:
      image: paymentservice
    params:
      <<: *cosign_credentials
    config:
      <<: *cosign_verify

- name: verify-productcatalogservice
  plan:
  - get: productcatalogservice  
    trigger: true
  - task: verify
    input_mapping:
      image: productcatalogservice
    params:
      <<: *cosign_credentials
    config:
      <<: *cosign_verify

- name: verify-recommendationservice
  plan:
  - get: recommendationservice  
    trigger: true
  - task: verify
    input_mapping:
      image: recommendationservice
    params:
      <<: *cosign_credentials
    config:
      <<: *cosign_verify

- name: verify-shippingservice
  plan:
  - get: shippingservice  
    trigger: true
  - task: verify
    input_mapping:
      image: shippingservice
    params:
      <<: *cosign_credentials
    config:
      <<: *cosign_verify

- name: bump-version
  plan:
  - get: adservice  
    trigger: true
    passed:
    - verify-adservice
  - get: cartservice  
    trigger: true
    passed:
    - verify-cartservice
  - get: checkoutservice  
    trigger: true
    passed:
    - verify-checkoutservice
  - get: currencyservice  
    trigger: true
    passed:
    - verify-currencyservice
  - get: emailservice  
    trigger: true
    passed:
    - verify-emailservice
  - get: frontend  
    trigger: true
    passed:
    - verify-frontend
  - get: paymentservice  
    trigger: true
    passed:
    - verify-paymentservice
  - get: productcatalogservice  
    trigger: true
    passed:
    - verify-productcatalogservice
  - get: recommendationservice  
    trigger: true
    passed:
    - verify-recommendationservice
  - get: shippingservice  
    trigger: true
    passed:
    - verify-shippingservice
  - get: version
    params:
      bump: patch
  - put: version
    params:
      file: version/version

- name: deploy-saas
  plan:
  - get: version
    trigger: true
    passed:
    - bump-version
  - load_var: version
    file: version/version
  - in_parallel:
      <<: *get_images
  - task:  deploy
    params:
      KUBECONFIG_JSON: ((saas.kubeconfig))
      DOCKERCONFIG_JSON: ((registry.config))
    config:
      platform: linux
      image_resource:
        source:
          repository: nixery.dev/shell/kubernetes-helm/yq-go/kubectl/kustomize/less/neovim
          tag: latest
        type: registry-image
      inputs:
      - name: adservice
      - name: cartservice
      - name: checkoutservice
      - name: currencyservice
      - name: emailservice
      - name: frontend
      - name: paymentservice
      - name: productcatalogservice
      - name: recommendationservice
      - name: shippingservice
      run:
        user: root
        path: bash
        args:
          - -c 
          - |
            umask 077
            mkdir ${HOME}/.kube
            echo "$KUBECONFIG_JSON" > ${HOME}/.kube/config

            mkdir ${HOME}/.docker
            echo "$DOCKERCONFIG_JSON" > ${HOME}/.docker/config.json

            function kustomize_service () {
              service=${1}
              
              digest=$(cat ${service}/digest)
              yq -i ".images += [ { \"name\": \"registry.shortrib.dev/online-boutique/${service}\", \"digest\": \"${digest}\" } ]" kustomization.yaml
            }

            cat <<SCRIPT > kustomize.sh
            #!/bin/bash
            cat > online-boutique.yaml
            kustomize build .
            SCRIPT
            chmod u+x kustomize.sh

            cat <<KUSTOMIZATION > kustomization.yaml
            resources:
            - online-boutique.yaml
            images: []
            patches:
            - target:
                kind: Deployment
              patch: |-
                - op: add
                  path: /spec/template/spec/imagePullSecrets
                  value: [{ name: registry }]
            KUSTOMIZATION

            helm version
            kustomize version
            kubectl get all -n online-boutique

            kustomize_service adservice
            kustomize_service cartservice
            kustomize_service checkoutservice
            kustomize_service currencyservice
            kustomize_service emailservice
            kustomize_service frontend
            kustomize_service paymentservice
            kustomize_service productcatalogservice
            kustomize_service recommendationservice
            kustomize_service shippingservice

            helm upgrade uncommon-starfish oci://registry.shortrib.dev/online-boutique/onlineboutique \
              --install --version 0.6.0 \
              --set images.repository=registry.shortrib.dev/online-boutique \
              --set loadGenerator.create=false \
              --post-renderer $(pwd)/kustomize.sh

- name: prepare-replicated
  plan:
  - get: current-release
  - get: next-release
  - in_parallel:
      <<: *get_images
  - get: version
    trigger: true
    passed:
    - bump-version
  - load_var: version
    file: version/version
  - task: update-image-tags
    config:
      platform: linux
      image_resource:
        source:
          repository: nixery.dev/shell/openssh/git/yq-go
          tag: latest
        type: registry-image
      inputs:
      - name: next-release
      - name: adservice
      - name: cartservice
      - name: checkoutservice
      - name: currencyservice
      - name: emailservice
      - name: frontend
      - name: paymentservice
      - name: productcatalogservice
      - name: recommendationservice
      - name: shippingservice
      outputs:
      - name: next-release
      run:
        user: root
        path: bash
        args:
          - -c 
          - |
            export SSH_KEY_DIR=$(pwd)/ssh

            cat <<COMMIT_MESSAGE > commit-message
            Automatically releases service updates

            TL;DR
            -----
            
            Creates new release for newly available service version(s)

            Details
            -------

            Updates images versions for the following services: 
            COMMIT_MESSAGE

            function update_image_hash() {
              service=${1}
              digest=$(cat ${service}/digest)
              manifest="next-release/manifests/${service}-chart.yaml"

              yq -i ".spec.values.images.tag = \"edge@${digest}\"" ${manifest}
              if [[ git diff --exit-code  ${manifest} 2>&1 1>/dev/null ]] ; then
                echo "* ${service}" >> commit-message
              fi
            }

            umask 077
            mkdir $SSH_KEY_DIR
            echo '((github.signing_priv_key))' >> ${SSH_KEY_DIR}/signingkey
            
            # this is a hack for now to get past an error, will likely need to switch
            # from the nixery image and build one with a passwd file in order to use SSH
            # to sign the commit
            echo 'root:*:0:0:System Administrator:/var/root:/bin/sh' > /etc/passwd

            update_image_hash adservice
            update_image_hash cartservice
            update_image_hash checkoutservice
            update_image_hash currencyservice
            update_image_hash emailservice
            update_image_hash frontend
            update_image_hash paymentservice
            update_image_hash productcatalogservice
            update_image_hash recommendationservice
            update_image_hash shippingservice

            cd next-release 
            git config --global user.name "Online Boutique Release Pipeline"
            git config --global user.email "chuck@replicated.com"
            git config --global user.signingkey ${SSH_KEY_DIR}/signingkey
            git config --global gpg.format ssh 
            git config --global commit.gpgsign true 

            git add manifests/*-chart.yaml
            git commit -m "$(cat commit-message)"
  - put: next-release
    params:
      repository: next-release
      branch: release-((.:version))

- name: merge-replicated
  plan:
  - get: next-release
    trigger: true
    passed:
    - prepare-replicated
  - get: version
    passed:
    - prepare-replicated
  - load_var: version
    file: version/version
  - task: create-pull-request
    params:
      GITHUB_TOKEN: ((github.password))
      RELEASE_BRANCH: release-((.:version))
    config:
      platform: linux
      image_resource:
        source:
          repository: nixery.dev/shell/git/gh
          tag: latest
        type: registry-image
      inputs:
      - name: next-release
      outputs:
      - name: pr
      run:
        user: root
        path: bash
        args:
          - -c 
          - |
            OUTPUT_DIR=$(pwd)/pr

            cd next-release
            gh auth login -h github.com
            gh pr create --head ${RELEASE_BRANCH} --fill \
              > ${OUTPUT_DIR}/url
  - task: merge-pull-request
    params:
      GITHUB_TOKEN: ((github.password))
    config:
      platform: linux
      image_resource:
        source:
          repository: nixery.dev/shell/git/gh
          tag: latest
        type: registry-image
      inputs:
      - name: next-release
      - name: pr
      run:
        user: root
        path: bash
        args:
          - -c 
          - |
            PR_URL=$(cat pr/url)

            set -x
            gh auth login -h github.com
            gh pr merge --merge --match-head-commit $(cat next-release/.git/ref) ${PR_URL}

- name: release-replicated
  plan:
  - get: next-release
    trigger: true
    passed:
    - merge-replicated
  - get: version
    passed:
    - merge-replicated
  - load_var: version
    file: version/version
  - task: release-app
    params:
      REPLICATED_APP: online-boutique
      REPLICATED_API_TOKEN: ((replicated.token))
      VERSION: ((.:version))
    config:
      platform: linux
      image_resource:
        source:
          repository: replicated/vendor-cli
          tag: latest
        type: registry-image
      inputs:
      - name: next-release
      run:
        user: root
        path: sh
        dir: next-release
        args:
          - -c 
          - |
            RELEASE_NOTES="$(cat .git/commit_message)"
    
            /replicated release create \
              --app ${REPLICATED_APP} \
              --token ${REPLICATED_API_TOKEN} \
              --version ${VERSION} \
              --release-notes "${RELEASE_NOTES}" \
              --yaml-dir manifests \
              --ensure-channel \
              --promote edge
