resources:
- name: source
  type: git
  icon: github
  source:
<<<<<<< HEAD
    uri: https://github.com/crdant/microservices-demo.git
=======
    uri: https://github.com/GoogleCloudPlatform/microservices-demo.git
>>>>>>> 6a857ae (Proivdes a build pipeline for the adservice)
    paths: 
    - src/adservice/**
- name: image
  type: registry-image
  icon: oci 
  source:
<<<<<<< HEAD
    repository: registry.shortrib.dev/online-boutique/adservice
    username: ((registry.robot))
    password: ((registry.token))
    tag: edge
=======
    repositoy: registry.shortrib.dev/online-boutique/adservice
    username: ((regisry.robot))
    password: ((resistry.token))
>>>>>>> 6a857ae (Proivdes a build pipeline for the adservice)

jobs:
- name: test
  plan:
<<<<<<< HEAD
  - get: source
=======
  - get: adservice
>>>>>>> 6a857ae (Proivdes a build pipeline for the adservice)
    trigger: true
  - task: check
    config:
      platform: linux
      inputs:
      - name: source
      image_resource:
<<<<<<< HEAD
        source:
          repository: gradle
          tag: 8.0.2-jdk19-jammy
=======
        name: ""
        source:
          repository: gradle
          tag: 8.0.2-jdk17-alpine
>>>>>>> 6a857ae (Proivdes a build pipeline for the adservice)
        type: registry-image
      caches:
      - path: $HOME/.m2/repository
      - path: $HOME/.gradle/caches/
      - path: $HOME/.gradle/wrapper/
      run:
        path: /bin/sh
        dir: source/src/adservice
        args:
        - -c
        - |
          java -Xmx32m -version
          javac -J-Xmx32m -version

          gradle wrapper
          ./gradlew test

- name: build
  plan:
  - get: source
    trigger: true
    passed:
    - test
  - task: build
    privileged: true
    output_mapping:
      image: build
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      params:
        CONTEXT: source/src/adservice        
      inputs:
      - name: source
      outputs:
      - name: image
      run:
        path: build
  - put: image
    params: 
      image: build/image.tar
  
- name: sign
  plan:
  - get: image
    trigger: true
    passed:
    - build
  - task: sign
    params:
      KUBECONFIG_JSON: ((kubeconfig))
      DOCKERCONFIG_JSON: ((registry.config))
    config:
      platform: linux
      image_resource:
        source:
          repository: gcr.io/projectsigstore/cosign
          tag: v2.0.0
        type: registry-image
      inputs:
      - name: image
      run:
        path: /busybox/sh
        args:
          - -c
          - |
            umask 077
            mkdir ${HOME}/.kube
            echo "$KUBECONFIG_JSON" > ${HOME}/.kube/config

            mkdir ${HOME}/.docker
            echo "$DOCKERCONFIG_JSON" > ${HOME}/.docker/config.json

            export DIGEST=$(cat image/digest)
            /ko-app/cosign version 
            /ko-app/cosign sign --yes --key k8s://concourse-online-boutique/signing-key registry.shortrib.dev/online-boutique/adservice@$DIGEST 
