---
apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: online-boutique
spec:
  groups:
  - name: services
    title: Services
    description: Configures the high-level parameters for the services
    items:
    - name: domain
      title: Domain
      help_text: "The base domain for exposed Online Boutique services"
      type: text
      required: true
  - name: tls
    title: TLS
    description: Enables TLS certificates for the exposed services
    items:
    - name: tls-issuer-type
      title: Issuer Type
      help_text: "Type of certificate issuer to use on to issue certificates"
      type: select_one
      items:
      - name: issuer
        title: Issuer
      - name: cluster-issuer
        title: Cluster Issuer
    - name: tls-issuer-name
      title: Issuer Name
      help_text: "Which issuer/cluster issuer should to use to generate certificates"
      type: text
      required: true
  - name: datastores
    title: Data Service Configuration
    description: Specifies details for service datastores 
    items:
    - name: redis_type
      type: select_one
      title: Redis
      default: embedded_redis
      items:
        - name: embedded_redis
          title: Embedded Redis
        - name: external_redis
          title: External Redis
    - name: external_redis_host
      title: Redis Host
      when: '{{repl ConfigOptionEquals "redis_type" "external_redis"}}'
      type: text
      default: redis
    - name: external_redis_port
      title: Redis Port
      when: '{{repl ConfigOptionEquals "redis_type" "external_redis"}}'
      type: text
      default: "6379"
