---
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: online-boutique
spec:
  title: Online Boutique
  icon: https://raw.githubusercontent.com/GoogleCloudPlatform/microservices-demo/main/src/frontend/static/icons/Hipster_HeroLogoMaroon.svg 
  statusInformers:
    - deployment/adservice
    - deployment/cartservice
    - deployment/checkoutservice
    - deployment/currencyservice
    - deployment/emailservice
    - deployment/frontend
    - deployment/paymentservice
    - deployment/productcatalogservice
    - deployment/recommendationservice
    - deployment/redis-cart
    - deployment/shippingservice
  replicatedRegistryDomain: registry.shortrib.io
  proxyRegistryDomain: proxy.shortrib.io
  ports:
    - serviceName: frontend
      servicePort: 80
      localPort: 8888
      applicationUrl: "http://frontend"
